### ISSUE TITLE
getargspec usage not 2.4/2.5 compliant

### ISSUE THREAD

**Issue by k0s** [mozilla/datazilla_client#24]
old inspect.getargspec returns a tuple:

Traceback (most recent call last):
  File "run_tests.py", line 298, in <module>
    main()
  File "run_tests.py", line 295, in main
    run_tests(parser)
  File "run_tests.py", line 271, in run_tests
    talos_results.output(results_urls, **results_options)
  File "/home/cltbld/talos-slave/talos-data/talos/results.py", line 77, in output
    _output.output(results, url)
  File "/home/cltbld/talos-slave/talos-data/talos/output.py", line 394, in output
    self.post(results, results_server, results_path, results_scheme)
  File "/home/cltbld/talos-slave/talos-data/talos/output.py", line 456, in post
    req = DatazillaRequest.create(scheme, server, project, self.oauth_key, self.oauth_secret, results)
  File "/home/cltbld/talos-slave/talos-data/talos/dzclient.py", line 155, in create
    attributes = inspect.getargspec(DatazillaResultsCollection.__init__).args[1:]
AttributeError: 'tuple' object has no attribute 'args'

For bug 763550 we should ensure that the old way works

**Comment by k0s** [comment]
https://github.com/mozilla/datazilla_client/pull/25
