### ISSUE TITLE
add more verbose output to diagnose failure in oauth.Request call

### ISSUE THREAD

**Issue by k0s** [mozilla/datazilla_client#26]
From https://bugzilla.mozilla.org/show_bug.cgi?id=789972:

Traceback (most recent call last):
  File "run_tests.py", line 298, in ?
    main()
  File "run_tests.py", line 295, in main
    run_tests(parser)
  File "run_tests.py", line 271, in run_tests
    talos_results.output(results_urls, **results_options)
  File "c:\talos-slave\talos-data\talos\results.py", line 78, in
  output
    _output.output(results, url)
  File "c:\talos-slave\talos-data\talos\output.py", line 391, in
  output
    self.post(results, results_server, results_path, results_scheme)
  File "c:\talos-slave\talos-data\talos\output.py", line 472, in post
    responses = req.submit()
  File "c:\talos-slave\talos-data\talos\dzclient.py", line 194, in
  submit
    responses.append(self.send(dataset))
  File "c:\talos-slave\talos-data\talos\dzclient.py", line 225, in
  send
    req = oauth.Request(method="POST", url=uri, parameters=params)
  File "c:\talos-slave\talos-data\talos\oauth2__init__.py", line 350,
  in **init**
    v = to_unicode_optional_iterator(v)
  File "c:\talos-slave\talos-data\talos\oauth2__init__.py", line 135,
  in to_unicode_optional_iterator
    assert 'is not iterable' in str(e)

I have not been able to reproduce this locally, so I'm not really sure what is causing this problem :(  The only thing I can think to do is to add debugging code to output the uri and params on failure and hopefully this can at least tell what the problem is o_O (That said, I would welcome better ideas)

A new datazilla client should be released to pypi for this issue

**Comment by k0s** [comment]
https://github.com/mozilla/datazilla_client/pull/27 merged
